### ISSUE TITLE
captcha support

### ISSUE THREAD

**Issue by dyu** [adtac/commento#1]
Since the comment is unauthenticated, having captcha would at least help.

**Comment by smbkr** [comment]
I have started looking at this - would reCaptcha invisible be suitable? If so, I'll give this a crack during my lunch breaks this week.

**Comment by adtac** [comment]
@smbkr Absolutely, all patches are welcome :) If you want, you can create a new issue and I'll assign it to you (of you can self-assign if you have permissions; idk how Github permissions work).

**Comment by mongrelion** [comment]
I was also thinking about reCaptcha (Google's) but the honeypot approach sounds easier and still elegant.

@smbkr good luck. Let me know if you need some guidance/help.

**Comment by dyu** [comment]
I've cloned the demo at http://dyu.gitlab.io/comments/
I haven't added captcha support yet.
Credit to @adtac for starting this project.

**Comment by adtac** [comment]
@dyu are you planning on implementing captcha?

**Comment by dyu** [comment]
@adtac I'll start looking around for existing oss solutions that are minimal and easy to integrate.

**Comment by chriscowley** [comment]
Please no, do not do Captcha, it is a horrible solution for everyone concerned.

https://boagworld.com/usability/my-definitive-guide-to-why-captcha-sucks/

**Comment by adtac** [comment]
@chriscowley currently, we have the honeypot technique mentioned in the article. Hopefully, we can add some basic spam filtering techniques on the backend. And finally, when the moderation dashboard is added, you can manually filter comments. These three should be sufficient in my opinion.

I have been mildly skeptical about implementing captcha (and recaptcha in particular; their privacy policy is completely in violation of what Commento stands for) for a while now. I'll still leave this issue open in case someone else wants to voice their opinion.

**Comment by adtac** [comment]
@dyu @smbkr @mongrelion @chriscowley I've decided we'll not be implementing reCaptcha (or any other captcha service, for that matter) in Commento.

We now have Akismet integration built into Commento with https://github.com/adtac/commento/pull/169. Askimet is probably the best at detecting and filtering spam as they have a huge corpus of what's spam and what's not, so this should stop most malicious users. If you're running a non-commercial website (a personal blog, for example), you can get an Akismet key for free. See [docs/akismet.md](../tree/master/docs/akismet.md) for more details on how to do this.

Closing this issue.
