### ISSUE TITLE
The Coral Project

### ISSUE THREAD

**Issue by gajus** [adtac/commento#100]
Seems exactly the same as the Coral Project, and Talk is far more advanced (feature wise)... https://coralproject.net/products/talk.html

**Comment by adtac** [comment]
Talk looks really cool! I looks like it predates Commento as well. I didn't know Mozilla had their own comment engine as well. I had applied for funding from Mozilla (to develop Commento), so this is going to be weird haha.

Interestingly, Talk never turned up when I was searching for Disqus alternatives back when I created Commento.

It does look like it's way more advanced. While Commento development has dipped recently, I'll be getting the project going soon enough (once I'm done with other stuff IRL). I'll be implementing most of the features Talk has such as moderation, better spam protection, and stuff (although I have had these on my mind even before you brought Talk to my attention).

I guess it's never bad to have more than one open-source alternative; it only improves both projects :D (See GCC/LLVM for example.)

**Comment by gajus** [comment]
> I guess it's never bad to have more than one open-source alternative; it only improves both projects :D (See GCC/LLVM for example.)

You say that, but there are hundreds already. Instead, the focus should be to create at least one solid alternative. Coral Project has been in development for long time.

Why they completely neglect any form of marketing the project? This is completely beyond me. Talk is being used by some of the biggest websites on the Internet.

**Comment by adtac** [comment]
>You say that, but there are hundreds already. Instead, the focus should be to create at least one solid alternative. Coral Project has been in development for long time.

Well, I wasn't aware of any at that time, so I don't really know I can do about it now.

>Why they completely neglect any form of marketing the project? This is completely beyond me. Talk is being used by some of the biggest websites on the Internet.

Maybe you should file an issue about that on the talk repo? :D

Closing this issue as it's not really one I'm personally concerned with. I still feel having alternatives is a good idea. Feel free to continue the discussion.
