### ISSUE TITLE
Tag Docker images

### ISSUE THREAD

**Issue by MrSaints** [adtac/commento#107]
It'd be great if there were versioned releases, and tagged Docker images. A few days ago, the Docker image, `adtac/commento:latest`, was not working. After pulling again, it worked. There's no guarantee that it can break again. 

On that note, it'd probably be wise to do some error logging rather than omitting `err` entirely.

**Comment by adtac** [comment]
Good point, I'll make a 0.1 release and tag that in docker.

**Comment by adtac** [comment]
A 0.1.0 docker tag exists now.

https://hub.docker.com/r/adtac/commento/tags/

**Comment by MrSaints** [comment]
Cheers @adtac
