### ISSUE TITLE
Use a modified preorder tree to render comments instead of each comment referencing parent

### ISSUE THREAD

**Issue by adtac** [adtac/commento#11]
Source: https://www.reddit.com/r/programming/comments/67fb80/commento_an_open_source_lightweight_and/dgqidle/

Reference link: https://www.sitepoint.com/hierarchical-data-database-2/

**Comment by StAmourD** [comment]
> The tradeoff is that inserts and moves are slow. If the structure of the tree is constantly changing, MPTT is not a good option because it needs to update many or all of the records. It also performs a whole table lock which prevents any updates to the affected table. This is obviously less than ideal if you have a heavily updated database.

[https://www.caktusgroup.com/blog/2016/01/04/modified-preorder-tree-traversal-django/](https://www.caktusgroup.com/blog/2016/01/04/modified-preorder-tree-traversal-django/)

**Comment by adtac** [comment]
Sounds like this feature is a no-go.

(BTW, we're moving all development [to GitLab](https://gitlab.com/commento/commento-ce).)
