### ISSUE TITLE
Automatically run `init` on load? (add your opinion)

### ISSUE THREAD

**Issue by adtac** [adtac/commento#129]
Not sure if this is a good idea.

Go through each `<script>` tag with `getElementByTagName` and see if the `src` attribute matches `.*commento\.(min\.)?js$`. If it does, extract the `serverUrl` from that string automatically.

**Comment by dertuxmalwieder** [comment]
My opinion:

While integrating Commento into [my blog software](https://bitbucket.org/tux_/blogcpp) (you're welcome), I found that it seemed unnecessary to set up the server URL twice - all other comment systems seem to do that in an easier way.

So my +1 goes into your good idea. :)

**Comment by adtac** [comment]
Thanks for integrating!

A snippet like:

```html
<div id="commento"></div>
<script defer src="https://server/commento.min.js" data-div="#commento"></script>
```

is what I'm considering. `data-div` would be a selector for the div to fill with comments.

**Comment by dertuxmalwieder** [comment]
Looks good!
