### ISSUE TITLE
Create AUR package

### ISSUE THREAD

**Issue by adtac** [adtac/commento#132]
Now that we have [binary release packages](https://github.com/adtac/commento/releases), I'm hoping someone experienced with the [AUR](https://aur.archlinux.org/) would create a PKGBUILD for the project. The .tar.gz that's downloadable for 0.1.0 has an amd64-linux binary and the assets directory.

**Comment by nkprince007** [comment]
Hey, @adtac it'd be awesome to have it for macOS (Homebrew) as well.

**Comment by adtac** [comment]
@nkprince007 we'll require the `assets/` directory in the targz as well. I'll use goreleaser to automatically build binaries for darwin-amd64 instead of your tarball; that okay?

And no, I'm not calling people using OS X idiots :P :P

**Comment by nkprince007** [comment]
Yeah, sure use goreleaser.

And it's not about macOS users, it's about [OSX Server](https://www.apple.com/in/macos/server/).

**Comment by adtac** [comment]
@grawlinson awesome! Lemme know if you need anything from my side.

**Comment by adtac** [comment]
@nkprince007 @grawlinson Thanks a lot for this issue!

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to (with a link back to this issue for history):
 - https://gitlab.com/commento/commento-ce/issues/30 - for Arch Linux (AUR)
 - https://gitlab.com/commento/commento-ce/issues/32 - for macOS

I'm closing this issue. Cheers!
