### ISSUE TITLE
Add support for permalinks to comments

### ISSUE THREAD

**Issue by nkprince007** [adtac/commento#145]
This would be nice addition as it lets us share content with other sites.

<img width="763" alt="screen shot 2017-12-04 at 1 05 36 am" src="https://user-images.githubusercontent.com/17202890/33528950-536df82c-d88f-11e7-831e-f5ed762ebc98.png">

Like that **alt-click** thingy on gitter.

**Comment by adtac** [comment]
@nkprince007 @davidak Thanks for this feature suggestion!

We have moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/36 (with a link back to this issue for history). Cheers!
