### ISSUE TITLE
How to add comment to specific URL?

### ISSUE THREAD

**Issue by modInfo** [adtac/commento#151]
How to add a comment to the page, use custom url address?

Would like to add a comment from http://example.com/ but should be added as http://anotherexample.com/post/

Is there a variable to present the url address?

```
window.onload = function() {
    Commento.init({
        serverUrl: "http://example.com/",
        pageUrl" "http://anotherexample.com/post/",
    });
}
```

**Comment by adtac** [comment]
This is currently not possible; Commento uses whatever url is present in the `document.location`. However, you're right, we should allow for custom IDs. We could even remove the limitation that this should be a URL: any unique ID would be sufficient (like `post-1234`).

**Comment by adtac** [comment]
I *think* this feature could be implemented entirely on the frontend (hence the `area/frontend` label), but if you think the backend has to be changed, lemme know and I'll add the label.

**Comment by klummy** [comment]
@adtac Hello, I will like to pick this up. Is anyone working on it already?

**Comment by adtac** [comment]
@klummy nope, it's all yours :)

**Comment by pjebs** [comment]
https://github.com/adtac/commento/issues/172

Any progress @klummy

**Comment by adtac** [comment]
Ideally, something like `<script src="https://blah.com/js/commento.min.js" data-id="whatever-you-want">` would work. If you don't give a `data-id`, `document.location` will be used.

**Comment by adtac** [comment]
@modInfo @pjebs @klummy Thanks a lot for this issue! This issue is still very much valid.

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/37 (with a link back to this issue for history). Cheers!
