### ISSUE TITLE
Website link not working

### ISSUE THREAD

**Issue by theel0ja** [adtac/commento#157]
![image](https://user-images.githubusercontent.com/5832930/36806666-7378d79e-1cc9-11e8-84a9-7fb6634c7ca1.png)

Same in Chrome

**Comment by theel0ja** [comment]
Found the problem..

![image](https://user-images.githubusercontent.com/5832930/36806737-aeb9b5d0-1cc9-11e8-846f-3f59a58a60af.png)

**Comment by theel0ja** [comment]
Reported to F-Secure about false positive

**Comment by adtac** [comment]
Thanks!

**Comment by theel0ja** [comment]
![](https://user-images.githubusercontent.com/5832930/36973842-2e23df56-207d-11e8-8a64-476e755de986.png)

**Comment by adtac** [comment]
Thanks a lot for your time and effort to get this approved, @theel0ja!
