### ISSUE TITLE
UX changes

### ISSUE THREAD

**Issue by limafoxtrottango** [adtac/commento#160]
The current UX looks a bit too primitive and brutalist. I think the developers and users would like the following changes alike:

1. Fix the comment box at the bottom. This way, the user does not have to scroll all the way up to make a comment.

2. A placeholder for the main comment text area.

3. Demarcation b/w parent comments.

**Comment by adtac** [comment]
@limafoxtrottango 

>Fix the comment box at the bottom. This way, the user does not have to scroll all the way up to make a comment.

I'm not sure if this is a good idea; I hate fixed div elements in webpages. Maybe others could weigh in?

>A placeholder for the main comment text area.

This feature has now been implemented! In the latest version of Commento (basically a rewrite), you now have a placeholder in the textarea :)

>Demarcation b/w parent comments.

I'm not sure I fully understand what kind of demarcation you want?

Anyway, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue; please feel free to re-open two issues in the GitLab repo for points 1 and 2 if you feel they're necessary. Others can add their comments (there, not here) too.
