### ISSUE TITLE
Due to default values in configuration file you can't choose a port using own env variables.

### ISSUE THREAD

**Issue by GotoFinal** [adtac/commento#162]
https://github.com/adtac/commento/blob/master/config.go#L13
and then all that values are moved to env: 
https://github.com/adtac/commento/blob/master/config.go#L36

So any values changed using "export" command or any other tool will be ignored.  
I don't think it should work like that... why use env values at all if you can't modify them outside application?

**Comment by adtac** [comment]
Right, there should be a `Getenv` check to see if the variable is already defined. If it's not, set it. So `export` > `.env.development.local` > `.env.test.local` > ... > `.env`.

Thanks for reporing! I'll fix this.
