### ISSUE TITLE
Difficulties setting different port

### ISSUE THREAD

**Issue by amca01** [adtac/commento#168]
As my port 8080 is in use, I've tried to start commento with each of the methods given for setting a different port.  Such as, for example:

    export COMMENTO_PORT=9000 
    ./commento

But in each case I get the error that the server cannot be started on port 8080.  That is, my attempts to change the port are ignored.  So - how do I start commento on a different port?  Thank you!

**Comment by adtac** [comment]
@amca01 are you using the latest release from master? This was a known bug in 0.2.1, but I fixed it a few days ago. I'll soon make a 0.2.2 release.

**Comment by adtac** [comment]
@amca01 [Commento v0.3.0](https://github.com/adtac/commento/releases/tag/v0.3.0) has been released. Can you please try out that version and report whether you're still facing this issue?

**Comment by amca01** [comment]
I had downloaded the latest release which was 0.2.1 then, but I've just downloaded 0.3.0, and the port is indeed changeable.  Thank you!  The difficulty I have now is managing a secure connection with https...

**Comment by adtac** [comment]
Awesome :+1: Closing this issue then :)

Re https: you may want to check out nginx+letsencrypt. That's what I'm using in https://commento.adtac.pw/ and it works flawlessly.
