### ISSUE TITLE
Different blog posts

### ISSUE THREAD

**Issue by pjebs** [adtac/commento#172]
How does commento allow us to indicate which page commento is operating on. That way the 1 database can work for all pages we want to use.

Am I missing something? I don't see it on the readme.

**Comment by pjebs** [comment]
If it uses the url path to identify and store which blog post, then perhaps a feature request is the ability for the developer to provide a identifier since the url path could change easily.

**Comment by adtac** [comment]
Yes, this is a fairly requested feature. Closing as it's a duplicate of https://github.com/adtac/commento/issues/151

Let's continue further discussion there :)
