### ISSUE TITLE
Webmention support?

### ISSUE THREAD

**Issue by kaushalmodi** [adtac/commento#180]
Hello,

Have you heard of [Indieweb][1]? It would be awesome if you can support sending [Webmentions][2] for posted comments. 

That would go better with your Commento hosting service. There, Commento will do the job of only saving the comments to the database, optionally saved in both pre-rendered plain text and HTML-rendered versions, and then just send a Webmention to the associated post.

The website owner will be then responsible for receiving those webmentions and displaying them as they wish (_Here's an [example][3] of how I display Webmentions._)

So Commento will be responsible for:

1. Receiving and saving the comments to the database.
2. Sending Webmentions.

Reference: A similar service - [anoweco][4] - that does this but implemented in PHP.

Would this fit in your future plan for development?

[1]: https://indieweb.org/
[2]: https://indieweb.org/Webmention
[3]: https://scripter.co/golang-quirk-number-strings-starting-with-0-are-octals/#webmentions
[4]: https://github.com/cweiske/anoweco

**Comment by adtac** [comment]
@kaushalmodi @mro thanks a lot for this issue! This is definitely still valid.

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/40 (with a link back to this issue for history).
