### ISSUE TITLE
Import comments from Disqus

### ISSUE THREAD

**Issue by jamesbvaughan** [adtac/commento#181]
A lot of commento users are likely coming from Disqus, and an awesome feature for commento would be the ability to pull in old comments. Disqus can export comments in a custom XML format explained here:
https://help.disqus.com/developer/comments-export

I might be able to try to add this in a few weeks, but if there are other people that would like this feature and can work on it sooner, that would be great!

**Comment by adtac** [comment]
@jamesbvaughan Thanks a lot for this issue! As you know, we already have Disqus import available in the new version (the rewrite).

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue. Cheers!
