### ISSUE TITLE
[Translation] How can I translate texts in commento on my site?

### ISSUE THREAD

**Issue by Mlocik97-issues** [adtac/commento#192]
Hello,

How can I translate commento on my site? for example I have button with text "ADD COMMENT" and I need translate it. I thought, I can do it by CSS -> content, but I can't see which selectors I need to use, how a lot of text I need to translate. Is there file, where are all texts and css selectors, which can use to translation?

**Comment by adtac** [comment]
Please use the [Gitlab tracker](https://gitlab.com/commento/commento/issues) for new issues. This Github repo is just a code mirror.

Here's the relevant issue on Gitlab: https://gitlab.com/commento/commento/issues/28

To answer your question, you can do this only after i18n is implemented. As I mentioned in the above issue:

>I'm sorry, but this isn't very high in my priority list. I understand that i18n is important (English isn't my first language, so I really understand), but right now I'm focusing on other features. I'll come back to this in a couple of month to think about how best I can solve this (unless someone beats me to it by submitting an MR :P)
