### ISSUE TITLE
Feature: Chrome extension to inject comments

### ISSUE THREAD

**Issue by tracker1** [adtac/commento#193]
Would be cool to see a chrome extension that injects comments for a site that doesn't offer them.  Similar to the dissenter extension.

**Comment by adtac** [comment]
<p align="center">:warning: &nbsp; <b>This is a mirror. All development takes place <a href="https://gitlab.com/commento/commento">on Gitlab</a>.</b></p>
<div>You're viewing the Github mirror of the <code>master</code> branch. All development and discussion takes place on <a href="https://gitlab.com/commento/commento">on Gitlab</a>, not on Github. Please submit all issues and patches over there.</div></td></tr>
