### ISSUE TITLE
Empty message

### ISSUE THREAD

**Issue by Tazeg** [adtac/commento#194]
We can write empty messages just by writing HTML code like `<p></p>`. It should be declined like when we click on ADD COMMENT with an empty textarea.

**Comment by adtac** [comment]
<p align="center">:warning: &nbsp; <b>This is a mirror. All development takes place <a href="https://gitlab.com/commento/commento">on Gitlab</a>.</b></p>
<div>You're viewing the Github mirror of the <code>master</code> branch. All development and discussion takes place on <a href="https://gitlab.com/commento/commento">on Gitlab</a>, not on Github. Please submit all issues and patches over there.</div></td></tr>
