### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by SergeyPirogov** [adtac/commento#195]
Is there any chance to go with mysql?

**Comment by adtac** [comment]
No, there are no plans to support multiple database backends.

<p align="center">:warning: &nbsp; <b>This is a mirror. All development takes place <a href="https://gitlab.com/commento/commento">on Gitlab</a>.</b></p>
<div>You're viewing the Github mirror of the <code>master</code> branch. All development and discussion takes place on <a href="https://gitlab.com/commento/commento">on Gitlab</a>, not on Github. Please submit all issues and patches over there.</div></td></tr>
