### ISSUE TITLE
Styles broken on Edge

### ISSUE THREAD

**Issue by marcushellberg** [adtac/commento#196]
Both comment and login styles are broken on MS Edge. 

These can be reproduced on https://demo.commento.io/

<img width="545" alt="Screen Shot 2019-04-08 at 2 15 18 PM" src="https://user-images.githubusercontent.com/883698/55757485-dddd0b00-5a08-11e9-9810-79d4da67eda9.png">
<img width="720" alt="Screen Shot 2019-04-08 at 2 15 06 PM" src="https://user-images.githubusercontent.com/883698/55757487-dddd0b00-5a08-11e9-9b25-30959a8924f9.png">

**Comment by adtac** [comment]
<p align="center">:warning: &nbsp; <b>This is a mirror. All development takes place <a href="https://gitlab.com/commento/commento">on Gitlab</a>.</b></p>
<div>You're viewing the Github mirror of the <code>master</code> branch. All development and discussion takes place on <a href="https://gitlab.com/commento/commento">on Gitlab</a>, not on Github. Please submit all issues and patches over there.</div></td></tr>
