### ISSUE TITLE
Author name links to defunct G+ page

### ISSUE THREAD

**Issue by marcushellberg** [adtac/commento#197]
G+ has been discontinued.

**Comment by adtac** [comment]
<p align="center">:warning: &nbsp; <b>This is a mirror. All development takes place <a href="https://gitlab.com/commento/commento">on Gitlab</a>.</b></p>
<div>You're viewing the Github mirror of the <code>master</code> branch. All development and discussion takes place on <a href="https://gitlab.com/commento/commento">on Gitlab</a>, not on Github. Please submit all issues and patches over there.</div></td></tr>
