### ISSUE TITLE
Limit nesting to a sane number

### ISSUE THREAD

**Issue by chimbosonic** [adtac/commento#20]
After multiple replies the comments become unreadable.
Multiple nesting replies make comments disappear.

PS great loading times for your demo considering the number of comments and the fact I loaded it over 3g

**Comment by adtac** [comment]
I've edited the title to "Limit nesting to a sane number" because I think that's more general.

This should be fairly easy to implement: compute the nest level at each insert (since we know the parent) and reject all inserts exceed a threshold.

What's a sane level? 5 levels below root?

**Comment by chimbosonic** [comment]
So on my phone it text escapes the box on the 7th reply
I added some screenshots

![screenshot_20170426-204030](https://cloud.githubusercontent.com/assets/5418177/25453540/3c52f1dc-2ac1-11e7-8b16-4faca81a8d0f.png)
![screenshot_20170426-204100](https://cloud.githubusercontent.com/assets/5418177/25453542/3c53cfbc-2ac1-11e7-81c5-876557089adc.png)

**Comment by franciscop** [comment]
I'd like to add what I did in [comments.network](https://comments.network/): first indent is pretty obvious, second one is smaller, etc until at certain point the indentation between them is really small. Not sure how that would work out with the border based boxes.

**Comment by adtac** [comment]
I've added https://github.com/adtac/commento/commit/9f3878245145e2abb76de178f797de561cf063c5 that fixes this. If you use the latest version of commento, comments will be limited to a depth of 6. If you try to reply to a level 6 comment, it'll actually be a reply to its parent. Example:

![img](https://cloud.githubusercontent.com/assets/7521600/25540934/6fb2dd44-2c6a-11e7-93f3-5c989837a8c4.png)

"6" was actually a reply to "5" but it'll get stored as a reply to "4". This is kinda like hackernews.
