### ISSUE TITLE
Do not indent the right side when nesting

### ISSUE THREAD

**Issue by adtac** [adtac/commento#21]
Thanks to https://news.ycombinator.com/item?id=14206261

**Comment by DarkThrone** [comment]
I have a commit for this one, but before I submit a PR I need either https://github.com/adtac/commento/pull/42 merged or https://github.com/adtac/commento/issues/11 submitted, reviewed and merged.

**Comment by adtac** [comment]
Not entirely sure if this is still relevant since we limit the nesting level. After a point (level 5, I think), all comments have the same parent and aren't nested anymore. Thus the indentation won't get out of hand.

Closing. Feel free to argue otherwise.
