### ISSUE TITLE
CSS outdated

### ISSUE THREAD

**Issue by michaelmior** [adtac/commento#23]
I get the error below when trying the snippet in the README. Looking at `vendor/commento.js`, it looks as though the version number is out of date.

`Failed to load resource: cdn.rawgit.com/adtac/commento/0.0.2/vendor/commento.min.css the server responded with a status of 404 ()`

**Comment by adtac** [comment]
This has been fixed  now, thanks for pointing out! :)

**Comment by michaelmior** [comment]
Thanks for the fix!
