### ISSUE TITLE
Comment length limit

### ISSUE THREAD

**Issue by adtac** [adtac/commento#34]
Someone posted the first few hundred thousand digits of pi :|

**Comment by peteretelej** [comment]
regarding these length limits; sqlite ignores any length limits e.g. varchar(1000) column is just like a TEXT column. To resolve this, comments may need truncating before saving in `createComment` 

```
if len(comment)>1000{
comment = comment[:1000]
}
```

& additionally adding a `max_length` to the comment form textarea

**Comment by adtac** [comment]
huh, I didn't know that :D 

I'll make a patch soon :+1:
