### ISSUE TITLE
block custom styling

### ISSUE THREAD

**Issue by caarlos0** [adtac/commento#37]
in order to avoid this:

![image](https://cloud.githubusercontent.com/assets/245435/25538303/938d251e-2c18-11e7-98f5-bf74b6606bd2.png)

**Comment by adtac** [comment]
Just pushed https://github.com/adtac/commento/commit/6dc9e5cab54f30a8ea1caa23f98a92d0c3e23246 that should fix it

**Comment by adtac** [comment]
Updating the demo server right now

**Comment by adtac** [comment]
Fixed
