### ISSUE TITLE
Demo comment deletion

### ISSUE THREAD

**Issue by Superman132** [adtac/commento#41]
The comments in the demo aren't getting deleted after 30 minutes. Some comments say that they were posted 10 hours ago, yet they are still shown on the web page.

**Comment by adtac** [comment]
Argh I must have forgotten to set the `DEMO` env variable.

**Comment by lccezinha** [comment]
Maybe #51 can fix this

**Comment by adtac** [comment]
I've fixed this in the demo. Comments are now deleted every hour instead of 30 mins.
