### ISSUE TITLE
Use simpler err printing

### ISSUE THREAD

**Issue by peteretelej** [adtac/commento#45]
The error logging and printing on emit & die functions is a bit verbose.

`fmt.Printf("%s", fmt.Errorf("%s", err))` only needs `fmt.Print(err)` or better `fmt.Println(err)`

and 'logger.Panic(fmt.Errorf("%s", err))` just `logger.Panic(err)`

**Comment by DarkThrone** [comment]
Since you are working on this issue, what about adding https://github.com/sirupsen/logrus or https://github.com/apex/log

That way we are standardising for log collection on logstash, Splunk and AWS.

**Comment by peteretelej** [comment]
@DarkThrone since this was a pretty straight-forward fix, decided to close this first, as we look into logging. What are your thoughts on apex/log as compared to logrus? I've only used logrus before
