### ISSUE TITLE
Use flags instead of environment variables for arguments

### ISSUE THREAD

**Issue by peteretelej** [adtac/commento#49]
Flags may be easier to manage and control for instances. 

``` go
var (
                port = flag.Int("port", 8080, "http server port")
                demo = flag.Bool("demo", false, "use commento demo server")
)

func main(){

flag.Parse()

// .. and usage
 if *demo {
                fmt.Println("clearing")
// ..
svr := &http.Server{
                Addr:         fmt.Sprintf(":%d", *port),
                ReadTimeout:  5 * time.Second,
                WriteTimeout: 10 * time.Second,
}
```

**Comment by GaiusMartius** [comment]
@adtac @peteretelej 

12 factor app philosophy will apply well for the case of commento. The entry on configuration is here
https://12factor.net/config

In short, store config in environment variables. One exception to this would be the port which could be specified on the commandline, a very common practice that also avoids clashing with other services having their ports specified in the environment.

**Comment by adtac** [comment]
That is a completely different way to rethink config files. Thanks for the link, @GaiusMartius 

I agree, the env vars config suits commento since we're mostly going to just use strings and numbers.

**Comment by adtac** [comment]
@GaiusMartius btw, we have a gitter chat room now: https://gitter.im/coala/coala

Feel free to pop in and say hello :)

**Comment by GaiusMartius** [comment]
Will do, Thanks adtac.

**Comment by peteretelej** [comment]
The env file and 12factor is cool and all, but is are config files it really worth it when we only have 2 arguments to pass in. flags or env variables with sensible defaults would make sense have less footprint and would not require sourcing a file on startup.  If the env files are just in case of future arguments remember "premature optimization is the root of all evil"

**Comment by adtac** [comment]
>If env dotfiles are just in case of future arguments remember "premature optimization is the root of all evil"

But that argument could be applied to pretty much any architectural planning. I think env files are an obvious choice when we decided to use the 12-factor technique. I do agree with the sensible defaults idea. We could have default values that could be overridden using env files or using `OPTION=foo ./commento`.
