### ISSUE TITLE
Fix loading page without comments

### ISSUE THREAD

**Issue by peteretelej** [adtac/commento#50]
Getting the following error is returned (console) if the url has no comments
```
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at _redraw (commento.js:198)
```

Trying to loop through comments when the no data is returned. Checking if data exists first may help ( at
`commento.js:191`)
``` javascript
var _redraw = function(comments) {
    if (comments===undefined){
        return;
    }
```

**Comment by DarkThrone** [comment]
IT's fixed on a PR that's in review!

**Comment by DarkThrone** [comment]
Fixed!
