### ISSUE TITLE
signal: killed

### ISSUE THREAD

**Issue by wmydz1** [adtac/commento#52]
It don't work!

**Comment by adtac** [comment]
@wmydz1 could you add more details? Please specify your OS, arch, what you did to build the server, how you executed the executable?

**Comment by wmydz1** [comment]
macos 10.12.4

**Comment by adtac** [comment]
>what you did to build the server

>how you executed the executable

Those too :P

**Comment by wmydz1** [comment]
go run *.go  
signal: killed

**Comment by wmydz1** [comment]
~ » cd /Users/samchen/Downloads/commento-master/              samchen@localhost
------------------------------------------------------------
~/Downloads/commento-master » go run *.go                     samchen@localhost
signal: killed
------------------------------------------------------------
~/Downloads/commento-master »                                 samchen@localhost

**Comment by adtac** [comment]
Did you pull the dependencies before executing? I'm not really sure why this might happen.

**Comment by wmydz1** [comment]
$ cd /Users/samchen/go/src/github.com/adtac/commento/
samchen@localhost:~/go/src/github.com/adtac/commento
master ✔ $ go build .
samchen@localhost:~/go/src/github.com/adtac/commento
master ✔ $ chmod 777 comment
chmod: comment: No such file or directory
samchen@localhost:~/go/src/github.com/adtac/commento
master ✔ $ chmod 777 commento                                               1 ↵
samchen@localhost:~/go/src/github.com/adtac/commento
master ✔ $ ./commento
[1]    88696 killed     ./commento
samchen@localhost:~/go/src/github.com/adtac/commento
master ✔ $ go version                                                     137 ↵
go version go1.8 darwin/amd64

**Comment by wmydz1** [comment]
go get -v github.com/adtac/commento
yes! I use this command before!

**Comment by adtac** [comment]
Found https://github.com/golang/go/issues/19734 that says that some macOS 10.12.4 builds fail. Can you try adding ` -ldflags -s` to `go build .`?

**Comment by adtac** [comment]
Or can you update to `go1.8.1` which is supposed to fix this?

**Comment by wmydz1** [comment]
Thanks! it works

**Comment by adtac** [comment]
Great, closing then :)
