### ISSUE TITLE
Use go-minify

### ISSUE THREAD

**Issue by adtac** [adtac/commento#69]
https://github.com/tdewolff/minify

Advantages:

 - easier development because we wouldn't need minified files in the repo at all - this will make development easier because we won't get conflicts on the min files
 - go would minify files on the fly

**Comment by adtac** [comment]
Maybe have an env var option (`SERVE_MINIFIED`, default `TRUE`) with which we can toggle minification.

**Comment by peteretelej** [comment]
how about instead of the addition env var `SERVE_MINIFIED`, we could serve unminified for demo/dev environment since dev implies testing

**Comment by adtac** [comment]
Someone in production *might* want to serve unminified files. This is rare, but it's good to have separate options IMO.

**Comment by adtac** [comment]
CC @DarkThrone because he had some ideas about the frontend pipeline

**Comment by DarkThrone** [comment]
Whoa, GH never sent an email notifying me about this mention. To be honest, I looked at go-minify, and the JS minifier is half implemented. The current solution (Uglify) is far superior in compression and reliability.

Serving unminified files to production could be used for debugging, but that it's not a problem that Commento should solve, that's just a bad practice and developers should avoid that altogether. We shouldn't encourage this practices. If there is a bug, they can either report it upstream, or clone the repo, fixit and send a PR.

**Comment by adtac** [comment]
I think we have solved this with uglify. Currently, running:

```bash
$ npm install
$ npm run-script build
```

should use uglify (through gulp) to minify all .js files (currently there's only one: commento.js).

The compression ratio is:

```bash
$ ls -hal assets/js
total 28K
drwxr-xr-x 1 adtac adtac   52 Oct 28 10:28 .
drwxr-xr-x 1 adtac adtac   26 Jun 13 19:42 ..
-rw-r--r-- 1 adtac adtac  17K Oct 28 10:28 commento.js
-rw-r--r-- 1 adtac adtac 5.4K Oct 27 21:23 commento.min.js
```

5.4/17 = 31%, which is pretty nice. If someone wants to propose a different minifier, feel free to open a new issue.
