### ISSUE TITLE
The command '/bin/sh -c go build -o commento .' returned a non-zero code: 1

### ISSUE THREAD

**Issue by modInfo** [adtac/commento#72]
Step 7/9 : RUN go build -o commento .
 ---> Running in 399c950c157b
can't load package: package commento: no buildable Go source files in /go/src/commento
The command '/bin/sh -c go build -o commento .' returned a non-zero code: 1

**Comment by modInfo** [comment]
mod@12:~/commento$ go get -v github.com/adtac/commento
can't load package: package github.com/adtac/commento: no buildable Go source files in /home/mod/gocode/src/github.com/adtac/commento

**Comment by GaiusMartius** [comment]
Dockerfile needs to be updated. @adtac intends to move main.go back to the root so the dockerfile will work again once that happens.

**Comment by adtac** [comment]
Current master's `docker build .` works

**Comment by adtac** [comment]
@modInfo can you check again with the latest master?
