### ISSUE TITLE
the live demo does not work

### ISSUE THREAD

**Issue by aoloe** [adtac/commento#80]
the live demo on https://adtac.github.io/commento/example/demo.html fails to load https://commento.now.sh/assets/js/commento.min.js

**Comment by GaiusMartius** [comment]
@adtac, was `npm install` and `npm run build` run?

I tried running this locally. I had to do the npm commands and then replace the commento.now.sh references with localhost:8080.

**Comment by adtac** [comment]
hmm, I'm using Docker to do the deployment. Looks like I forgot to do run the `npm` stuff in the Dockerfile.

Opened https://github.com/adtac/commento/pull/86 - this should fix it. Once it does, I'll redeploy.

**Comment by brandondrew** [comment]
Just a reminder: this is still broken. @adtac

**Comment by adtac** [comment]
Yeah, I just haven't got around to fixing it. I'm using now.sh's free server and Docker to deploy, but their service has been acting up for the past few days (docker pushes aren't working for whatever reason).

If you have a spare server running that you can volunteer for this, please let me know :) It's just a docker deployment running a go service on one port.

Meanwhile I'll look into other solutions.

**Comment by adtac** [comment]
Ok I've temporarily patched it with a hacky solution :3 

I'll implement something better over the weekend.

**Comment by adtac** [comment]
I created a digitalocean droplet to host the demo: it's so much better now and it works perfectly. Check out http://adtac.pw:8002/
