### ISSUE TITLE
Replace the goto in http.go with helper functions

### ISSUE THREAD

**Issue by adtac** [adtac/commento#9]
Quoting /u/go255 ([link](https://www.reddit.com/r/golang/comments/67blza/commento_an_open_source_lightweight_and/dgqjxe8/

>And I'm not a fan of your use of `goto end` in the `http.go` file and it's web handlers. You could had easily rewritten:

	end:
	result.Comments = comments
	json, _ := json.Marshal(result)
	w.Header().Set("Access-Control-Allow-Origin", "*")
	fmt.Fprintf(w, "%s", string(json))

>Into a helper function and call it/return instead of relying on the `goto`.

**Comment by peteretelej** [comment]
How about creating a result receiver method that writes the response:

``` go
type resultContainer struct {
        Success  bool      `json:"success"`
        Message  string    `json:"message"`
        Comments []Comment `json:"comments,omitempty"`
}

func (res *resultContainer) render(w http.ResponseWriter) {
        if res == nil {
                res = &resultContainer{false, "Some internal error occurred", nil}
        }
        w.Header().Set("Access-Control-Allow-Origin", "*")

        json, err := json.Marshal(res)
        if err != nil {
                w.Write([]byte(`{"Success":false,"Message":"Internal Server Error"}`))
                return
        }
        w.Write(json)
}

```
