### ISSUE TITLE
Support for Github/GitLab Pages

### ISSUE THREAD

**Issue by jco2** [adtac/commento#96]
Hello,

Anyone using Github/Gitlab Pages that would be interested in using Commento? [Staticman already does this](https://github.com/eduardoboucas/staticman#setting-up-a-repository), I think it would be nice to have this feature in Commento!

**Comment by adtac** [comment]
@jco2 do you supporting static pages served with github/gitlab pages? You can embed Commento on any HTML page with a simple `<script>` call; and that includes github/gitlab pages. However you need to run Commento on one of your own servers as a backend.

Or did you mean to ask for a service that'll just work with github/gitlab pages (without you having to bother with setting up a backend server)? If so, I am going to build such a service soon ;)

**Comment by jco2** [comment]
I meant the latter. You know what? that's awesome! Thanks a lot!

**Comment by nkprince007** [comment]
@adtac any progress on the service?

**Comment by adtac** [comment]
@nkprince007 it's coming soon™ :P A safe release date would some time early next year.

**Comment by adtac** [comment]
@jco2 @nkprince007 @dgl1 Sorry for the delay, https://commento.io has been in private beta for the past few months! Feel free to add yourself to the waiting list on the homepage :)

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue as I'm moving all issues to GitLab. Cheers!
