### ISSUE TITLE
Internationalization/Localization Support

### ISSUE THREAD

**Issue by AkshayAgarwal007** [adtac/commento#97]
From a brief overview, it looks like currently everything is hard-coded in English but one would want to use commento in sites which are not in English. This would require:

* Localizing the UI strings (things like 'Post Comment' , 'Reply' etc.)
* Formatting relative dates in a locale independent manner.
* Maybe a config parameter can be added to force a particular locale or detect the browser's locale preferences with fallback to a default locale.

Also, currently there is some bug which causes the timestamp to be displayed as '-2 seconds ago' (note the minus sign) just as a comment is posted.

**Comment by adtac** [comment]
@AkshayAgarwal007 thanks for the issue!

I'm pretty sure I've fixed the '-2s seconds ago' issue with https://github.com/adtac/commento/pull/117 - it'll display 'just now' for comments that were posted less than 5 seconds ago (for which -2 definitely qualifies).

The localization support featuer is still up for grabs if anyone wants to implement!

**Comment by adtac** [comment]
@AkshayAgarwal007 Thanks a lot for the issue! This is definitely still possible.

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/28 (with a link back to this issue for history). Cheers!
